<?xml version="1.0" encoding="utf-8"?><Database Name="database" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\database.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="PolyChocolates.Properties.Settings" SettingsPropertyName="databaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Traceability" Member="Traceabilities">
    <Type Name="Traceability">
      <Column Name="TraceabilityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InventoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountUsed" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Inventory_Traceability" Member="Inventory" ThisKey="InventoryId" OtherKey="InventoryId" Type="Inventory" IsForeignKey="true" />
      <Association Name="ProductEntry_Traceability" Member="ProductEntry" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Checklist" Member="Checklists">
    <Type Name="Checklist">
      <Column Name="ChecklistId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodeDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Initials" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Complete" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChocolateBarWeight" Member="ChocolateBarWeights">
    <Type Name="ChocolateBarWeight">
      <Column Name="ChocolateBarWeightId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChocolateQualityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bar1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Bar2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Bar3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Bar4" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Bar5" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ChocolateQuality_ChocolateBarWeight" Member="ChocolateQuality" ThisKey="ChocolateQualityId" OtherKey="ChocolateQualityId" Type="ChocolateQuality" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChocolateControl" Member="ChocolateControls">
    <Type Name="ChocolateControl">
      <Column Name="ChocolateControlId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MilkMachine1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MilkMachine2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DarkMachine" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Temper" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Appearance" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Flavor" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TasteTest" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ProductEntry_ChocolateControl" Member="ProductEntry" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChocolateQuality" Member="ChocolateQualities">
    <Type Name="ChocolateQuality">
      <Column Name="ChocolateQualityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MilkMachine1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MilkMachine2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DarkMachine" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Temper" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Appearance" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Flavor" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TasteTest" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ChocolateQuality_ChocolateBarWeight" Member="ChocolateBarWeights" ThisKey="ChocolateQualityId" OtherKey="ChocolateQualityId" Type="ChocolateBarWeight" />
      <Association Name="ProductEntry_ChocolateQuality" Member="ProductEntry" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="Customer_Invoice" Member="Invoices" ThisKey="CustomerId" OtherKey="CustomerId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Efficiency" Member="Efficiencies">
    <Type Name="Efficiency">
      <Column Name="EfficiencyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActualYield" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ItemWeight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Efficiency_EfficiencyWaste" Member="EfficiencyWastes" ThisKey="EfficiencyId" OtherKey="EfficiencyId" Type="EfficiencyWaste" />
      <Association Name="ProductEntry_Efficiency" Member="ProductEntry" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EfficiencyWaste" Member="EfficiencyWastes">
    <Type Name="EfficiencyWaste">
      <Column Name="EfficiencyWasteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EfficiencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WasteType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Efficiency_EfficiencyWaste" Member="Efficiency" ThisKey="EfficiencyId" OtherKey="EfficiencyId" Type="Efficiency" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="InventoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PricePerUnit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PreviousStock" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Stock" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ActualUsage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PredictedUsage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Supplier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Certificate" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SnapshotDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LotCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Inventory_Traceability" Member="Traceabilities" ThisKey="InventoryId" OtherKey="InventoryId" Type="Traceability" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Invoice_InvoiceRow" Member="InvoiceRows" ThisKey="InvoiceId" OtherKey="InvoiceId" Type="InvoiceRow" />
      <Association Name="Customer_Invoice" Member="Customer" ThisKey="CustomerId" OtherKey="CustomerId" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceRow" Member="InvoiceRows">
    <Type Name="InvoiceRow">
      <Column Name="InvoiceRowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RatePer" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CreditAccount" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeDate" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceRow" Member="Invoice" ThisKey="InvoiceId" OtherKey="InvoiceId" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductEntry" Member="ProductEntries">
    <Type Name="ProductEntry">
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductEntryVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecipeEntryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AmountPackaged" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountProduced" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Downtime" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductionNotes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentManager" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlantManager" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QualityPerformer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QualityControlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Complete" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="haacp" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ProductEntry_Traceability" Member="Traceabilities" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="Traceability" />
      <Association Name="ProductEntry_ChocolateControl" Member="ChocolateControls" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ChocolateControl" />
      <Association Name="ProductEntry_ChocolateQuality" Member="ChocolateQualities" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ChocolateQuality" />
      <Association Name="ProductEntry_Efficiency" Member="Efficiencies" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="Efficiency" />
      <Association Name="ProductEntry_ProductQualityEntryQual" Member="ProductQualityEntryQuals" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductQualityEntryQual" />
      <Association Name="ProductEntry_ProductQualityEntryQuant" Member="ProductQualityEntryQuants" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductQualityEntryQuant" />
      <Association Name="QualityControl_ProductEntry" Member="QualityControl" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="QualityControl" IsForeignKey="true" />
      <Association Name="Recipe_ProductEntry" Member="Recipe" ThisKey="RecipeEntryId" OtherKey="RecipeId" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductQualityEntryQual" Member="ProductQualityEntryQuals">
    <Type Name="ProductQualityEntryQual">
      <Column Name="ProductQualityEntryQualId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QualityLabelQualId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SustainTakeAction" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ProductEntry_ProductQualityEntryQual" Member="ProductEntry" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductEntry" IsForeignKey="true" />
      <Association Name="QualityLabelQual_ProductQualityEntryQual" Member="QualityLabelQual" ThisKey="QualityLabelQualId" OtherKey="QualityLabelQualId" Type="QualityLabelQual" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductQualityEntryQuant" Member="ProductQualityEntryQuants">
    <Type Name="ProductQualityEntryQuant">
      <Column Name="ProductQualityEntryQuantId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductEntryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QualityLabelQuantId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ProductEntry_ProductQualityEntryQuant" Member="ProductEntry" ThisKey="ProductEntryKey" OtherKey="ProductEntryKey" Type="ProductEntry" IsForeignKey="true" />
      <Association Name="QualityLabelQuant_ProductQualityEntryQuant" Member="QualityLabelQuant" ThisKey="QualityLabelQuantId" OtherKey="QualityLabelQuantId" Type="QualityLabelQuant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QualityControl" Member="QualityControls">
    <Type Name="QualityControl">
      <Column Name="QualityControlId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="QualityControl_ProductEntry" Member="ProductEntries" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="ProductEntry" />
      <Association Name="QualityControl_QualityLabelQual" Member="QualityLabelQuals" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="QualityLabelQual" />
      <Association Name="QualityControl_QualityLabelQuant" Member="QualityLabelQuants" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="QualityLabelQuant" />
      <Association Name="QualityControl_Recipe" Member="Recipes" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="Recipe" />
    </Type>
  </Table>
  <Table Name="dbo.QualityLabelQual" Member="QualityLabelQuals">
    <Type Name="QualityLabelQual">
      <Column Name="QualityLabelQualId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QualityControlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttributeTesting" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="QualityLabelQual_ProductQualityEntryQual" Member="ProductQualityEntryQuals" ThisKey="QualityLabelQualId" OtherKey="QualityLabelQualId" Type="ProductQualityEntryQual" />
      <Association Name="QualityControl_QualityLabelQual" Member="QualityControl" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="QualityControl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QualityLabelQuant" Member="QualityLabelQuants">
    <Type Name="QualityLabelQuant">
      <Column Name="QualityLabelQuantId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QualityControlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Test" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Aim" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sustain" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TakeAction" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Abort" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="QualityLabelQuant_ProductQualityEntryQuant" Member="ProductQualityEntryQuants" ThisKey="QualityLabelQuantId" OtherKey="QualityLabelQuantId" Type="ProductQualityEntryQuant" />
      <Association Name="QualityControl_QualityLabelQuant" Member="QualityControl" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="QualityControl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recipe" Member="Recipes">
    <Type Name="Recipe">
      <Column Name="RecipeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TraceabilityRequired" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EfficiencyRequired" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="QualityControlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpectedWeight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="haccp" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="Recipe_ProductEntry" Member="ProductEntries" ThisKey="RecipeId" OtherKey="RecipeEntryId" Type="ProductEntry" />
      <Association Name="Recipe_RecipeIngredient" Member="RecipeIngredients" ThisKey="RecipeId" OtherKey="RecipeId" Type="RecipeIngredient" />
      <Association Name="Recipe_RecipeStep" Member="RecipeSteps" ThisKey="RecipeId" OtherKey="RecipeId" Type="RecipeStep" />
      <Association Name="QualityControl_Recipe" Member="QualityControl" ThisKey="QualityControlId" OtherKey="QualityControlId" Type="QualityControl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecipeIngredient" Member="RecipeIngredients">
    <Type Name="RecipeIngredient">
      <Column Name="RecipeIngredientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ingredient" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Recipe_RecipeIngredient" Member="Recipe" ThisKey="RecipeId" OtherKey="RecipeId" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecipeSteps" Member="RecipeSteps">
    <Type Name="RecipeStep">
      <Column Name="RecipeStepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StepNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StepInstructions" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Recipe_RecipeStep" Member="Recipe" ThisKey="RecipeId" OtherKey="RecipeId" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
</Database>